In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# importing dataset

In [26]:
data = pd.read_csv("Social_Network_Ads.csv")
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [27]:
print(data)
print(X)
print(y)

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]
     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]
0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64


In [28]:
# splitting to train and test set

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [31]:
# Scaling the salary and age
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
print(X_test[-10:])
# age/estimated salary

[[-0.70230411  1.30752418]
 [ 0.81073886  0.72986826]
 [ 0.43247812 -0.16549842]
 [-0.41860856 -0.3099124 ]
 [ 0.33791293 -0.22326401]
 [ 0.99986923 -1.0897479 ]
 [ 0.71617367  1.74076612]
 [-0.04034781  0.00779835]
 [-0.41860856 -0.56985757]
 [-0.22947818  0.18109513]]


In [38]:
# Importing Logistic Regression lib
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

In [50]:
# Training the model
classifier.fit(X_train, y_train)

LogisticRegression()

In [56]:
# Predicting the result probability
classifier.predict_proba(X_test)

array([[0.28888154, 0.71111846],
       [0.90462754, 0.09537246],
       [0.76035608, 0.23964392],
       [0.78674834, 0.21325166],
       [0.97124577, 0.02875423],
       [0.02979803, 0.97020197],
       [0.81847027, 0.18152973],
       [0.91293618, 0.08706382],
       [0.74169191, 0.25830809],
       [0.35062387, 0.64937613],
       [0.47539651, 0.52460349],
       [0.11201726, 0.88798274],
       [0.99027083, 0.00972917],
       [0.75587254, 0.24412746],
       [0.39345859, 0.60654141],
       [0.34487882, 0.65512118],
       [0.59127502, 0.40872498],
       [0.5234065 , 0.4765935 ],
       [0.11200269, 0.88799731],
       [0.14871911, 0.85128089],
       [0.95150178, 0.04849822],
       [0.03890022, 0.96109978],
       [0.15300134, 0.84699866],
       [0.99815646, 0.00184354],
       [0.99789325, 0.00210675],
       [0.96674011, 0.03325989],
       [0.99253798, 0.00746202],
       [0.77967223, 0.22032777],
       [0.99432494, 0.00567506],
       [0.95340879, 0.04659121],
       [0.

In [51]:
# Predicting the result classify
classifier.predict(X_test)

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [55]:
print(sc.transform([[36,33000]]))
classifier.predict(sc.transform([[36,33000]]))

[[-0.134913  -1.0897479]]


array([0], dtype=int64)

In [78]:
# Predicted vs Real results
y_pred = classifier.predict(X_test)
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(-1, 1),y_test.values.reshape(-1, 1)),1))

[[1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


In [80]:
# Make the confusion matrix (matrix to show no of correct vs incorrect)

In [85]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[57  4]
 [13 26]]


0.83