In [2]:
# Importing Libraries
import pandas as pd
import tensorflow as tf
import numpy as np

In [3]:
# Importing dataset
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# Preprocessing data
X = dataset.iloc[:, 3:-1].values  # Removing customerid and surname from feature
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
# Encoding categorical data

In [8]:
# for gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
# One hot encoding for geography
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
# Splitting to train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
# Feature Scale
# Note: it is very important to scale the features while using ANNs
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)

[[ 0.99252792 -0.57369368 -0.57523331 ...  0.65114845 -1.02429504
  -0.28884592]
 [ 0.99252792 -0.57369368 -0.57523331 ... -1.53574811 -1.02429504
  -0.63940387]
 [-1.00752834 -0.57369368  1.73842505 ...  0.65114845 -1.02429504
  -1.49125989]
 ...
 [-1.00752834 -0.57369368  1.73842505 ...  0.65114845 -1.02429504
   0.20361912]
 [-1.00752834  1.74309049 -0.57523331 ...  0.65114845  0.97628121
  -0.39428193]
 [-1.00752834 -0.57369368  1.73842505 ... -1.53574811  0.97628121
  -0.69863788]]


In [12]:
# Building the ANN

In [13]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [14]:
# Adding the input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [15]:
# Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu")) # hidden layer 

In [16]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) # units = 1 for binary output and sigmoid for probability of output

In [17]:
# Training the ANN

In [18]:
# compiling the ANN
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

In [19]:
# Training the ANN
ann.fit(X_train, y_train, batch_size=32, epochs=50)

Epoch 1/50
250/250 [==============================] - 0s 783us/step - loss: 0.5259 - accuracy: 0.7970
Epoch 2/50
250/250 [==============================] - 0s 632us/step - loss: 0.4624 - accuracy: 0.7970
Epoch 3/50
250/250 [==============================] - 0s 652us/step - loss: 0.4378 - accuracy: 0.7997
Epoch 4/50
250/250 [==============================] - 0s 820us/step - loss: 0.4226 - accuracy: 0.8176
Epoch 5/50
250/250 [==============================] - 0s 644us/step - loss: 0.4146 - accuracy: 0.8191
Epoch 6/50
250/250 [==============================] - 0s 676us/step - loss: 0.4090 - accuracy: 0.8202
Epoch 7/50
250/250 [==============================] - 0s 724us/step - loss: 0.4051 - accuracy: 0.8221
Epoch 8/50
250/250 [==============================] - 0s 915us/step - loss: 0.4018 - accuracy: 0.8239
Epoch 9/50
250/250 [==============================] - 0s 927us/step - loss: 0.3989 - accuracy: 0.8255
Epoch 10/50
250/250 [==============================] - 0s 860us/step - loss: 0.395

In [20]:
# Predictions

In [21]:
# Single Prediction
print(ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.05192649]]


In [22]:
# We can see that the probablity is very low (above) for customer to leave the bank

In [23]:
# Predicting on test
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [24]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   73]
 [ 232  181]]


0.8475